import './globals.css'
import type { Metadata } from 'next'
import LayoutFooter from './components/commons/layout/footer/footer'
import MainBar from './components/commons/layout/header/mainbar'
import NavBar from './components/commons/layout/header/navbar'
import SearchButton from './components/commons/layout/header/searchButton'
import SignupButton from './components/commons/layout/header/signupButton'
import { ModalProvider } from './components/commons/modal/modal-context-ex'
import { getServerSession } from 'next-auth'
import { options } from '@/app/api/auth/[...nextauth]/option'
import NextAuthProvider from '@/app/components/commons/session/SessionProvider'
export const metadata: Metadata = {
  title: 'Wanted',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // session (회원정보)
  const session = await getServerSession(options)
  console.log(session)

  return (
    <html lang="en">
      <body className={``}>
        <NextAuthProvider>
          <ModalProvider>
            <div className="top-0 left-0 right-0 fixed bg-white border border-b-stone-200">
              <div className="flex justify-around items-center ml-16 mr-16">
                <MainBar />
                <NavBar />
                <SignupButton />
                <SearchButton />
              </div>
            </div>
            <main className="mt-14">{children}</main>
            <LayoutFooter />
          </ModalProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
