import './globals.css'
import type { Metadata } from 'next'
import LayoutFooter from './components/commons/layout/footer/footer'
import MainBar from './components/commons/layout/header/mainbar'
import NavBar from './components/commons/layout/header/navbar'
import SearchButton from './components/commons/layout/header/searchButton'
import { ModalProvider } from './components/commons/modal/modal-context-ex'
import NextAuthProvider from '@/app/components/commons/session/SessionProvider'
import Login from '@/app/components/commons/layout/header/login'
export const metadata: Metadata = {
  title: 'Wanted',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={``}>
        <NextAuthProvider>
          <ModalProvider>
            <div className="top-0 left-0 right-0 fixed bg-white border border-b-stone-200 h-14 z-50 ">
              <div className="flex justify-around items-center ml-16 mr-16 h-14">
                <MainBar />
                <NavBar />
                <Login></Login>
                <SearchButton />
              </div>
            </div>
            <main className="mt-14 relative">{children}</main>
            <LayoutFooter />
          </ModalProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
